# This is a basic workflow to help you get started with Actions

name: Run Postman Inwarrenty Flow collection

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:  # Syntax one
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  push: # Syntax two
    branches: 
      - main
  pull_request:
    branches: 
      - main
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Setting up the CRON timings
  schedule:
    - cron: 30 2 * * 1-5
    - cron: 0 14 * * 1-5

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the code
      - uses: actions/checkout@v4

      # Install node.js
      - name: Install node.js
        uses: actions/setup-node@v6.1.0
        with:
          node-version: 22

       # Install newman
      - name: Install newman
        run: 
          npm install -g newman

       # Install newman-reporter-htmlextra
      - name: Install modern html reporter
        run: 
          npm install -g newman-reporter-htmlextra

       # Above two steps can be clubed together
      # - name: Install newman and newman-reporter-htmlextra
      #   run: |
      #     npm install -g newman
      #     npm install -g newman-reporter-htmlextra

      # Run the collection 
      - name: Run the inwarrenty flow collection
        run: |
          newman run 'Phoenix-Inwarrenty-Flow.postman_collection.json' \
          -e 'QA.postman_environment.json' \
          -r cli,htmlextra

